apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingpong-log-output-claim
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: pingpong-log-output
