apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingpong-log-output-claim
  namespace: exercises
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: pingpong-log-output


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-assets-claim
  namespace: project
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: project-assets
